### ISSUE TITLE
Improve styling of Bokeh web application

### ISSUE THREAD

**Issue by mrocklin** [dask/distributed#311]
@birdsarah and I sat down together and went over the aesthetics of the web ui.  Here is a record of feedback.  Generally I think our strategy here should be to wait until the next release of Bokeh is near, then implement these, then release.  Hopefully we can get someone (perhaps @birdsarah) to do these changes.

- [ ] Remove dual axis from resource plot.  Replace with two plots
- [ ] Provide variance bands around mean/cpu/network lines to show variance, possibly also show outliers
- [ ] Move the legend off canvas
- [ ] Use fewer tickers on the y-axes
- [ ] Add axes labels
- [ ] Keep resource chart near resource table so that they can refer to each other

- [ ] Move progress bar to the top
- [ ] Move the `/tasks` page to a tab in the same page.  Add an explicit "refresh" button

- [ ] Use responsive layouts, remove resize buttons

- [ ] Add brief prose between sections

### task plots

- [ ] Soften outlines around task bars.  We still need a little something here, but perhaps it could just be a slight changing of opacity or color rather than stark gray
- [ ] Make tasks slightly transparent and add a grid line on each worker, this might add a sense of continuity
- [ ] Remove y-ticks entirely, they're confusing when we destroy and add workers
- [ ] Reconsider the colors.  We have two reds sometimes.

### Tables

- [ ] Merge the tables into a single table, make this thinner by specifying column widths
- [ ] Perhaps put the table into an accordian

**Comment by mrocklin** [comment]
This has been resolved.
