### ISSUE TITLE
[WIP] Flaky tests overview

### ISSUE THREAD

**Issue by fjetter** [dask/distributed#5818]
I'm going over all known flaky tests and try to summarize them here such that this can serve as an overview.

Repeated offender
- [ ] `test_client_timeout` https://github.com/dask/distributed/issues/5703
- [ ] `test_adapt_quickly` https://github.com/dask/distributed/issues/5682

Xfailed
- [ ] https://github.com/dask/distributed/issues/5621
- [ ] `test_stress_creation_and_deletion` https://github.com/dask/distributed/issues/5388
- [ ] `test_stress_creation_and_deletion` https://github.com/dask/distributed/issues/5388 https://github.com/dask/distributed/issues/5172
- [ ] `test_no_threads_lingering` https://github.com/dask/distributed/issues/5049
- [ ] `test_restart_during_computation` https://github.com/dask/distributed/issues/4956

Skipped randomly
- [ ] `test_map` https://github.com/dask/distributed/issues/5007

Marked rerun / flaky
- [ ] `test_statistical_profiling` https://github.com/dask/distributed/issues/4974
- [ ] `test_steal_twice` https://github.com/dask/distributed/issues/4957
- [ ] `test_AllProgress_lost_key` https://github.com/dask/distributed/issues/4915
- [ ] 

More than 2 weeks stable
- [ ] `test_avoid_paused_workers` https://github.com/dask/distributed/issues/5613
- [ ] `test_aliases_2` https://github.com/dask/distributed/issues/5516
- [ ] `test_reschedule_concurrent_requests_deadlock` https://github.com/dask/distributed/issues/5494

GPU
- [ ] `test_ucx_protocol[1234]` https://github.com/dask/distributed/issues/5542
- [ ] `test_gpu_monitoring_recent` https://github.com/dask/distributed/issues/5287
- [ ] `test_secede_rejoin_busy` https://github.com/dask/distributed/issues/5275
- [ ] `test_ucx_config_w_env_var` https://github.com/dask/distributed/issues/5229
